### ISSUE TITLE
Store pictures for animals in database

### ISSUE THREAD

**Issue by aidan-bailey** [aidanjbailey/Anidopt#3]
### Description

Animals need pictures!

### Notes

- Pictures will be stored in the database.
- Size of pictures will currently just be 2GB as that is the maximum size of a VARBINARY field.
- Each animal can have zero to many pictures with zero to one main picture selected (to be displayed on the grid card).
- The picture table will have the schema: (Id: int, Bytes: ByteArray, AnimalId: int, Main: bool). 

### TODO

- [x] Create picture table.
- [x] Create picture service.
- [x] Create picture controller/views.
- [ ] Add to Animal controller/view.
